### ISSUE TITLE
unable to access any page on my system without seeing "The wkhtmltopdf-i386 binary could not be detected anywhere."

### ISSUE THREAD

**Issue by kojaktaha** [LukeTowers/oc-snappypdf-plugin#2]
I transferred my project to a new server and I can't get to any page in my project without seeing the error:

"The wkhtmltopdf-i386 binary could not be detected anywhere. Please manually specify the path to this binary through the SNAPPY_TYPE_BINARY environment variables or by setting the paths in config/luketowers/snappypdf/config.php"

sorry I am a noob with no idea what to do!!

**Comment by LukeTowers** [comment]
@kojaktaha this error is because the plugin cannot find an instance of the wkhtmltopdf binary (the actual wkhtmltopdf program that does the conversions) anywhere on your server in the predetermined places where it could be. 

First question, what server did you transfer it to? What OS is it using? What version of PHP? 

Second question, did you install this plugin from the marketplace or composer?

Third question, check your permissions on the binary files required for this to work. They could be in plugins/luketowers/snappypdf/vendor/bin, or they could be in plugins/luketowers/snappypdf/vendor/h4cc/*/bin or they could be in vendor/bin, or they could be in vendor/h4cc/*/bin.

**Comment by kojaktaha** [comment]
1st question: Local server (XAMPP) , Windows 10, 7.2.3.
2nd : Marketplace Backend=>Settings=>plugins and updates.
3rd: regular file permissions are applied on the other files (plugins/luketowers/snappypdf/vendor/bin), just to confirm i changed the permission to everyone if that could help, still stuck!

NOTES:
* I just downloaded a fresh OctoberCMS installation and still see the error when downloading the plugin (it is the only one downloaded from a fresh OctoberCMS.
* I use the web installer for installing OctoberCMS in both projects.

**Comment by LukeTowers** [comment]
@kojaktaha that explains it, this plugin doesn't support Windows officially yet. Please try using the [windows support](https://github.com/LukeTowers/oc-snappypdf-plugin/tree/windows-support) branch and see if that works for you. In order to use it you will have to setup your project to use Composer and then run `composer require luketowers/oc-snappypdf-plugin:dev-windows-support`
